// User data
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Property data
export const GET_PROPERIES = 'GET_PROPERIES';
export const GET_PROPERTY = 'GET_PROPERTY';
export const DELETE_PROPERTY = 'DELETE_PROPERTY';
export const ADD_PROPERTY = 'ADD_PROPERTY';
export const UPDATE_PROPERTY = 'UPDATE_PROPERTY';
export const PROPERTY_ERROR = 'PROPERTY_ERROR';
export const CLEAR_PROPERTY = 'CLEAR_PROPERTY';

// Price data
export const GET_PRICES = 'GET_PRICES';
export const GET_PRICE = 'GET_PRICE';
export const ADD_PRICE = 'ADD_PRICE';
export const DELETE_PRICE = 'DELETE_PRICE';
export const PRICE_ERROR = 'PRICE_ERROR';

// HousingCondition data
export const GET_HOUSING_CONDITION = 'GET_HOUSING_CONDITION';
export const ADD_HOUSING_CONDITION = 'ADD_HOUSING_CONDITION';
export const DELETE_HOUSING_CONDITION = 'DELETE_HOUSING_CONDITION';
export const HOUSING_CONDITION_ERROR = 'HOUSING_CONDITION_ERROR';

// EXTRA_FACILITY data
export const GET_EXTRA_FACILITY = 'GET_EXTRA_FACILITY';
export const ADD_EXTRA_FACILITY = 'ADD_EXTRA_FACILITY';
export const DELETE_EXTRA_FACILITY = 'DELETE_EXTRA_FACILITY';
export const EXTRA_FACILITY_ERROR = 'EXTRA_FACILITY_ERROR';

// Booking data
export const GET_BOOKING = 'GET_BOOKING';
export const ADD_BOOKING = 'ADD_BOOKING';
export const DELETE_BOOKING = 'DELETE_BOOKING';
export const BOOKING_ERROR = 'BOOKING_ERROR';

// BasicFacility data
export const GET_BASIC_FACILITY = 'GET_BASIC_FACILITY';
export const ADD_BASIC_FACILITY = 'ADD_BASIC_FACILITY';
export const DELETE_BASIC_FACILITY = 'DELETE_BASIC_FACILITY';
export const BASIC_FACILITY_ERROR = 'BASIC_FACILITY_ERROR';

// AdditionalFeature data
export const GET_ADDITIONAL_FEATURE = 'GET_ADDITIONAL_FEATURE';
export const ADD_ADDITIONAL_FEATURE = 'ADD_ADDITIONAL_FEATURE';
export const DELETE_ADDITIONAL_FEATURE = 'DELETE_ADDITIONAL_FEATURE';
export const ADDITIONAL_FEATURE_ERROR = 'ADDITIONAL_FEATURE_ERROR';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_REPOS = 'GET_REPOS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFIL_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const UPDATE_LIKES = 'UPDATE_LIKES';

export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';